name: Build
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Prepare environment
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet publish TaskbarShortcutGroups.sln -r win-x64 -f net8.0-windows -c Release --nologo -maxcpucount:1

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TaskbarShortcutGroup
          path: |
            TaskbarShortcutGroups.AvaloniaUI\bin\Release\net8.0-windows\win-x64\publish
            !**\*.pdb